---
title: "Causal Inference Project"
author: "Bjarke Hautop, Cecilie Krongaar, Ferdinand Roesen"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, warning=FALSE, message=FALSE}
library(dplyr)
library(fixest)
library(ivDiag)
```


# Load and clean data

```{r load data}
data <- readRDS("exam_TWEA1.R")

head(data)
```

Start with only using the variables described in the assignment?

```{r subset data}
subset_data <- data %>%
  select(
    uspto_class, grntyr, count_cl, anypatent, count_usa, count_cl_itt,
    mainclass_id, subcl, twea
  )
```


```{r head}
head(subset_data)
```

anypatent, mainclass_id, subcl, and twea need to be factors.

```{r convert to factors}
subset_data$anypatent <- as.factor(subset_data$anypatent)
subset_data$mainclass_id <- as.factor(subset_data$mainclass_id)
subset_data$subcl <- as.factor(subset_data$subcl)
subset_data$twea <- as.factor(subset_data$twea)
```

# 2SLS

```{r 2SLS with AER package}
library(AER)

# First-stage regression: Check relevance of instrument
first_stage <- lm(count_cl ~ count_cl_itt, data = subset_data)
summary(first_stage)  # Check significance of count_cl_itt

# 2SLS estimation
iv_model <- ivreg(count_usa ~ count_cl | count_cl_itt, data = subset_data)
summary(iv_model)
```

Using ivDiag package, see https://yiqingxu.org/packages/ivDiag/articles/iv_tutorial.html#estimation-and-inference


```{r first stage plot}
# Plot the instrument (X-axis) against the treatment (Y-axis)
par(mar = c(4, 4, 2, 2))  # Adjust margins for a clean plot
plot(
  subset_data$count_cl_itt, subset_data$count_cl,
  col = "#777777", cex = 0.5, 
  main = "First-Stage Raw",
  xlab = "Instrument (AP)",
  ylab = "Treatment (PA)"
)

# Add the fitted regression line
abline(first_stage, col = "red", lwd = 2, lty = 2)
```

```{r 2SLS with ivDiag package}
g <- ivDiag(
  data = subset_data, 
  Y = "count_usa", 
  D = "count_cl", 
  Z = "count_cl_itt", 
  controls = NULL, 
  cl = NULL,
  bootstrap = FALSE,
  run.AR = FALSE
)
names(g)
```

```{r}
g$est_ols
```

```{r}
g$est_2sls
```

```{r}
g$F_stat
```

```{r}
g$est_fs
```

```{r}
plot_coef(g)
```

# 2SLS with controls

```{r first stage plot (partial out)}
# first stage (partial out)
z_res <- lm(count_cl_itt ~ mainclass_id + twea, data = subset_data)$residuals
d_res <- lm(count_cl ~ mainclass_id + twea, data = subset_data)$residuals
plot(z_res, d_res, col = "#777777", cex = 0.5, 
     main = "First stage Covariates Partialled Out", 
     xlab = "Residualized Instrument (AP)", 
     ylab = "Residualized Treatment (PA)")
abline(lm(d_res ~ z_res), col = 2, lwd = 2, lty = 2)
```

```{r 2SLS with controls}
controls <- c("mainclass_id", "twea")
g_controls <- ivDiag(
  data = subset_data, 
  Y = "count_usa", 
  D = "count_cl", 
  Z = "count_cl_itt", 
  controls = controls, 
  cl = NULL,
  bootstrap = FALSE,
  run.AR = FALSE
)
names(g_controls)
```

```{r}
g_controls$est_ols
```

```{r}
g_controls$est_2sls
```

```{r}
g_controls$F_stat
```

```{r}
g_controls$est_fs
```

```{r}
plot_coef(g_controls)
```
